# Generated by Django 6.0.4 on 2026-04-21 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(900)])),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'brand'],
                'constraints': [models.CheckConstraint(condition=models.Q(('calories_per_100g__gte', 0)), name='food_calories_non_negative'), models.CheckConstraint(condition=models.Q(('protein_per_100g__gte', 0)), name='food_protein_non_negative'), models.CheckConstraint(condition=models.Q(('carbs_per_100g__gte', 0)), name='food_carbs_non_negative'), models.CheckConstraint(condition=models.Q(('fat_per_100g__gte', 0)), name='food_fat_non_negative'), models.CheckConstraint(condition=models.Q(('fiber_per_100g__gte', 0)), name='food_fiber_non_negative'), models.UniqueConstraint(fields=('name', 'brand'), name='food_unique_name_brand')],
            },
        ),
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5000)])),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('LUNCH', 'Comida'), ('DINNER', 'Cena'), ('SNACK', 'Snack')], default='LUNCH', max_length=12)),
                ('consumed_at', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_consumptions', to='evaluations.dailyrecord')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='nutrition.food')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['daily_record', 'meal_type'], name='nutrition_f_daily_r_2f852a_idx'), models.Index(fields=['food'], name='nutrition_f_food_id_5ad338_idx')],
            },
        ),
    ]
