# Generated by Django 6.0.4 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]

