# Generated by Django 6.0.4 on 2026-05-15 00:00

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_food_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="default_unit",
            field=models.CharField(
                choices=[("GRAM", "Gramos"), ("PORTION", "Racion")],
                default="GRAM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="portion_g",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="portion_label",
            field=models.CharField(blank=True, default="racion", max_length=40),
        ),
        migrations.AddField(
            model_name="foodconsumption",
            name="portion_count",
            field=models.DecimalField(
                blank=True,
                null=True,
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]

