# Generated by Django 6.0.4 on 2026-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_food_portions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="image_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]

