# Generated by Django 6.0.4 on 2026-04-21 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('met_value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(25)])),
                ('intensity', models.CharField(choices=[('LOW', 'Baja'), ('MODERATE', 'Moderada'), ('HIGH', 'Alta')], default='MODERATE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('calories_burned_estimated', models.PositiveIntegerField(blank=True, null=True)),
                ('performed_at', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='evaluations.dailyrecord')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='activity.physicalactivity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['daily_record', 'activity'], name='activity_ac_daily_r_be1422_idx'), models.Index(fields=['activity'], name='activity_ac_activit_7c9edc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('calories_burned_estimated__gte', 0), ('calories_burned_estimated__isnull', True), _connector='OR'), name='activity_record_calories_non_negative')],
            },
        ),
    ]
